# action.yml
name: 'Sphinx Docs build with ReadTheDocs Docker Image'
description: 'entrypoint.sh tries to mimic RTD build process using RTD Dockerfile, and if used as Github Action Sphinx _build output is made available in /github/workspace. Dockerfile is also usable locally for your own builds.'
inputs:
  rtd-prj-name: 
    description: |
      ReadTheDocs project name - also used as name for pdfs and epubs. 
      NOTE: you don't need to actually have a project on readthedocs servers!    
    default: 'myproject'
    required: true
  git-url:
    description: 'Full git url to clone the repo'
    required: true
  git-tag:
    description: 'tag or branch'    
    default: master
    required: false
  version:
    description: 'version as named on the website'    
    default: latest  
    required: false
  requirements: 
    description: 'requirements file for pip install'    
    default: 'requirements.txt'
  language: 
    description: 'Documentation language'    
    default: 'en'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rtd-prj-name }}
    - ${{ inputs.git-url }}
    - ${{ inputs.git-tag }}
    - ${{ inputs.version }}
    - ${{ inputs.requirements }}
    - ${{ inputs.language }}
    