# action.yml
name: 'Sphinx Docs build in Github Actions with ReadTheDocs Docker'
description: 'Tries to reproduce build in Githhub Actions with the same environment as in ReadTheDocs server. Also useful for local build.'
inputs:
  RTD_PRJ_NAME: 
    description: |
      ReadTheDocs project name - also used as name for pdfs and epubs. 
      NOTE: you don't need to actually have a project on readthedocs servers!    
    default: 'myproject'
    required: true
  GIT_URL:
    description: 'Full git url to clone the repo'
    required: true
  GIT_TAG:
    description: 'tag or branch'    
    default: master
    required: false
  VERSION:
    description: 'version as named on the website'    
    default: latest  
    required: false
  REQUIREMENTS: 
    description: 'requirements file for pip install'    
    default: 'requirements.txt'
  LANGUAGE: 
    description: 'Documentation language'    
    default: 'en'
    required: false
  RTD_HTML_SINGLE:
    description: 'builds single page html for offline use. Requires built project to have readthedocs_ext.readthedocs  sphinx extension'    
    default: true
    required: false
  RTD_HTML_EXT:
    description: 'builds html exactly as in RTD website. Requires built project to have readthedocs_ext.readthedocs sphinx extension'
    default: true
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.RTD_PRJ_NAME }}
    - ${{ inputs.GIT_URL }}
    - ${{ inputs.GIT_TAG }}
    - ${{ inputs.VERSION }}
    - ${{ inputs.REQUIREMENTS }}
    - ${{ inputs.LANGUAGE }}
    - ${{ inputs.RTD_HTML_SINGLE }}
    - ${{ inputs.RTD_HTML_EXT }}
    